Em sampler doc
Quantmetry/qolmat pull request #61
Opened 2023-07-21 08:26 UTC by hlbotterman

2023-08-09 11:56 UTC, JulienRoussel77 requested changes

2023-08-09 11:56 UTC, JulienRoussel77 commented on tests/imputations/test_em_sampler.py
> +    em_sampler.EM()
La classe EM est virtuelle, ce n'est pas grave si elle ne peut pas être initialisée

2023-08-09 11:56 UTC, JulienRoussel77 commented on tests/imputations/test_em_sampler.py
> +    assert np.sum(np.abs(data["mean"] - mean_imputed)) / np.sum(np.abs(data["mean"])) < 1e-1
Plutôt utiliser np.testing.assert_allclose

2023-08-24 15:04 UTC, hlbotterman commented on qolmat/benchmark/missing_patterns.py
> +        Creare the groups based on the column names (groups attribute)
manuel, je ne sais plus pourquoi. J'ai remis comme précédemment

2023-08-24 15:07 UTC, hlbotterman commented on examples/test_EM.md
Ah oui, erreur de ma part car je n'avais pas du tout l'intention de commit

2023-08-24 15:34 UTC, hlbotterman commented on qolmat/imputations/em_sampler.py
> +        # Rubin's rule
ok, changement dans l'autre PR

2023-08-24 15:34 UTC, hlbotterman commented on qolmat/imputations/em_sampler.py
> +            X = self.create_lag_matrix_X(X)
ok, changement dans l'autre PR

2023-08-28 09:52 UTC, merged